services:
  zookeeper:
    #container_name: zookeeper
    hostname: zookeeper
    image: confluentinc/cp-zookeeper:latest
    expose:
      - "2181"
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: "0.5"
  kafka:
    #container_name: kafka
    image: confluentinc/cp-kafka:latest
    env_file:
      - ./envs/kafka.env
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094"
    volumes:
      - kafka-data:/var/lib/kafka/data
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: "1.0"
  kafka-ui:
    #container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8085:8080
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      DYNAMIC_CONFIG_ENABLED: "true"
    deploy:
      resources:
        limits:
          memory: 256M
          cpus: "0.5"
  producer-kafka-client:
    container_name: producer-kafka-client
    build:
      context: ./producer
      dockerfile: Dockerfile
    depends_on:
      - kafka
  consumer-kafka-client:
    container_name: consumer-kafka-client
    build:
      context: ./consumer
      dockerfile: Dockerfile
    depends_on:
      - kafka
volumes:
  zookeeper-data: {}
  zookeeper-logs: {}
  kafka-data: {}
